import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SigninButton } from "./components/SigninButton";
import { HomeButton } from "./components/HomeButton";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
          {/* {children} */}
          <div>

            <nav>
              <div className="navbar bg-base-100">
                <div className="navbar-start">
                  <div className="dropdown">
                    <div tabIndex={0} role="button" className="btn btn-ghost lg:hidden">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        className="h-5 w-5"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M4 6h16M4 12h8m-8 6h16" />
                      </svg>
                    </div>
                  </div>
                  {/* <button onClick={handleHome} className="btn btn-ghost text-xl">Fortran Auction 🏠</button> */}
                  <HomeButton />
                </div>

                <SigninButton />
                {/* <div className="navbar-end">
                </div> */}
              </div>
            </nav>

            <main className="p-4 flex items-center justify-center">
              {children}
            </main>

            </div>
      </body>
    </html>
  );
}
